name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
      - 'feature/*' 
      - testing 
    
    pull_request:
    branches:
      - main  
      - 'feature/*' 
      - testing  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-


    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest tests

    - name: Build Docker images
      run: |
        docker build -t my-fastapi-app-web1 ./src
        docker build -t my-fastapi-app-web2 ./src
        docker build -t my-fastapi-app-nginx -f ./nginx/Dockerfile .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker images
      run: |
        docker tag my-fastapi-app-web1 my-dockerhub-username/my-fastapi-app-web1:latest
        docker tag my-fastapi-app-web2 my-dockerhub-username/my-fastapi-app-web2:latest
        docker tag my-fastapi-app-nginx my-dockerhub-username/my-fastapi-app-nginx:latest
        docker push my-dockerhub-username/my-fastapi-app-web1:latest
        docker push my-dockerhub-username/my-fastapi-app-web2:latest
        docker push my-dockerhub-username/my-fastapi-app-nginx:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to server
      run: |
        ssh user@server "docker pull my-dockerhub-username/my-fastapi-app-web1:latest && \
                          docker pull my-dockerhub-username/my-fastapi-app-web2:latest && \
                          docker pull my-dockerhub-username/my-fastapi-app-nginx:latest && \
                          docker-compose down && \
                          docker-compose up -d"
